# Set base image
FROM ubuntu:latest

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install required version of GLIBCXX
RUN apt-get update && apt-get install -y \
    libstdc++6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install additional dependencies for rendering
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables for rendering
ENV DISPLAY=:99
ENV PYTHONUNBUFFERED=1

# Start Xvfb server for virtual screen rendering
CMD ["Xvfb", ":99", "-screen", "0", "1024x768x16", "-ac", "+extension", "GLX", "+render", "-noreset"]

# Clone Git repository
RUN git clone https://github.com/Aortz/SA-PPO.git /app/my_project

# Set working directory
WORKDIR /app

# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniconda3-latest-Linux-x86_64.sh

# Add Conda to the path
ENV PATH="/opt/conda/bin:${PATH}"

# Copy environment.yml file
COPY environment.yml .

# Create Conda environment and activate it
RUN conda env create -f environment.yml && \
    echo "conda activate $(head -1 environment.yml | cut -d' ' -f2)" >> ~/.bashrc && \
    /bin/bash -c "source ~/.bashrc"

# Install OpenAI Gym
RUN pip install gym

# Set default command
CMD ["bash"]

# Set the entry point
# ENTRYPOINT ["conda", "run", "-n", "gym_env", "python"]
ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]