# Set the base image
FROM continuumio/miniconda3:latest

# Set the working directory
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install dependencies
RUN conda update conda && \
    conda create -n gym_env python=3.8 && \
    conda init bash &&\
    exec bash &&\
    conda activate gym_env && \
    pip install -r requirements.txt && \
    conda install pytorch torchvision torchaudio cpuonly -c pytorch

# Install OpenAI Gym
RUN apt-get update && \
    apt-get install -y xvfb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install gym && \
    pip install pyvirtualdisplay && \
    pip install gym[atari]

# Set the entry point
ENTRYPOINT ["conda", "run", "-n", "gym_env", "python"]
